update-openzeppelin:
	# Rather than playing around with git submodules, we're just doing this for now.
	curl -L -o contracts/OpenZeppelin/Account.cairo https://raw.githubusercontent.com/OpenZeppelin/cairo-contracts/main/contracts/Account.cairo
	curl -L -o utils/OpenZeppelin/Signer.py https://raw.githubusercontent.com/OpenZeppelin/cairo-contracts/main/tests/utils/Signer.py

	curl -L -o contracts/OpenZeppelin/ERC20.cairo https://raw.githubusercontent.com/OpenZeppelin/cairo-contracts/main/contracts/token/ERC20.cairo
	curl -L -o contracts/OpenZeppelin/IERC20.cairo https://raw.githubusercontent.com/OpenZeppelin/cairo-contracts/main/contracts/token/IERC20.cairo
